name: Build

on:
  release:
    types:
      - created

jobs:
  setup-capacitor-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies and initialize Capacitor
        run: |
          npm install
          npx cap init android
  
      - name: Set up JDK 21
        uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '21'

      - name: Print Java version
        run: java -version
        

      - name: Decode Keystore from Base64
        run: echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore

      - name: Find debug keystore
        run: |
          debug_keystore_path="${{ github.workspace }}/cookie.keystore"
          if [ -f "$debug_keystore_path" ]; then
            echo "Debug Keystore: $debug_keystore_path"
          else
            echo "Debug Keystore not found."
          fi

      - name: Give execute permission to gradlew
        run: chmod +x ./android/gradlew

      - name: Build the React application
        run: npm run build

      - name: Sync files with Capacitor
        run: npx cap sync

      - name: Verify Capacitor platform
        run: npx cap ls

      - name: Install apksigner
        run: sudo apt update && sudo apt install -y apksigner

      - name: Build Android
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          SIGNING_STORE_PASSWORD: cookieukw
          SIGNING_KEY_ALIAS: cookieukw
          SIGNING_KEY_PASSWORD: cookieukw
         
        run: |
          cd android
          ./gradlew bundleRelease
          ./gradlew assembleRelease 
           cd app/build/outputs/
           for apk in $(find . -name "*.apk"); do
             apksigner sign --v2-signing-enabled true --ks $ANDROID_KEYSTORE_PATH --ks-pass pass:$ANDROID_KEYSTORE_PASSWORD --ks-key-alias $ANDROID_KEY_ALIAS --key-pass pass:$ANDROID_KEY_PASSWORD --out "${apk%.apk}-signed.apk" $apk
          done
    

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
                ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
                ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.PIXEL }} 